image: quay.io/tike/alpine-oc-node

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

# Define a hidden job to be used with extends
# Better than default to avoid activating cache for all jobs
.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

# Define the stages
stages:
  - setup
  - deploy

# Define the process for setup stage
setup:
  stage: setup
  tags:
    - ohtu-build-3
  script:
    - sudo npm cache clean --force
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    name: $CI_COMMIT_REF_NAME
    expire_in: 1h
    paths:
      - node_modules

deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: development
  only:
    - main
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-dev --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-dev --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_TEST_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-dev dc/organisaatiorekisteri-api-dev
    - oc set env dc/organisaatiorekisteri-api-dev API_DB_HOST=$API_DB_HOST_DEV
    - oc set env dc/organisaatiorekisteri-api-dev API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_DEV
    - oc set env dc/organisaatiorekisteri-api-dev OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env dc/organisaatiorekisteri-api-dev OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env dc/organisaatiorekisteri-api-dev TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-dev --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_test:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: testing
  only:
    - test
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-test --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-test --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_TEST_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-test dc/organisaatiorekisteri-api-test
    - oc set env dc/organisaatiorekisteri-api-test API_DB_HOST=$API_DB_HOST_TEST
    - oc set env dc/organisaatiorekisteri-api-test API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_TEST
    - oc set env dc/organisaatiorekisteri-api-test OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env dc/organisaatiorekisteri-api-test OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env dc/organisaatiorekisteri-api-test TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-test --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-test --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-test --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_prod:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: production
  only:
    - prod
  when: manual
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_PROD:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_PROD
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-prod --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-prod --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_PROD_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-prod dc/organisaatiorekisteri-api-prod
    - oc set env dc/organisaatiorekisteri-api-prod API_DB_HOST=$API_DB_HOST_PROD
    - oc set env dc/organisaatiorekisteri-api-prod API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_PROD
    - oc set env dc/organisaatiorekisteri-api-prod OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env dc/organisaatiorekisteri-api-prod OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env dc/organisaatiorekisteri-api-prod TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-prod --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-prod --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-prod --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_organisation_dev:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: development
  only:
    - organisation-dev
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-dev --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-dev --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_TEST_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-dev dc/organisation-api-dev
    - oc set env dc/organisation-api-dev API_DB_HOST=$API_DB_HOST_ORGANISATION_DEV
    - oc set env dc/organisation-api-dev API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_ORGANISATION_DEV
    - oc set env dc/organisation-api-dev OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env dc/organisation-api-dev OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env dc/organisation-api-dev TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisation-api-dev --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisation-api-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisation-api-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
