image: quay.io/tike/alpine-oc-node

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

# Define a hidden job to be used with extends
# Better than default to avoid activating cache for all jobs
.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

# Define the stages
stages:
  - setup
  - deploy

# Define the process for setup stage
setup:
  stage: setup
  tags:
    - ohtu-build-1
  script:
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 1h
    paths:
      - node_modules

deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-1
  environment:
    name: development
  only:
    - main
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    # list environment variables here
    - oc set env dc/organisaatiorekisteri-api-dev API_DB_HOST=$API_DB_HOST_DEV
    - oc set env dc/organisaatiorekisteri-api-dev API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_DEV
    - oc set env dc/organisaatiorekisteri-api-dev OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env dc/organisaatiorekisteri-api-dev OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-dev --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
