image: quay.io/tike/alpine-oc-node

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

# Define a hidden job to be used with extends
# Better than default to avoid activating cache for all jobs
.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

# Define the stages
stages:
  - setup
  - dependency-check
  - sonarqube-check
  - deploy

# Define the process for setup stage
setup:
  stage: setup
  tags:
    - ohtu-build-3
  script:
    - npm ci
    - npm cache clean --force
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    name: $CI_COMMIT_REF_NAME
    expire_in: 1h
    paths:
      - node_modules

# Dependency-Check Stage
dependency-check:
  stage: dependency-check
  only:
    - main
  tags:
    - ohtu-build-3
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  script:
    - >
      /usr/share/dependency-check/bin/dependency-check.sh
      --project orgrek-ou-service --scan .
      --format JSON --format HTML  -nvdApiKey $NVD_API_KEY
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - dependency-check-report.json
      - dependency-check-report.html

sonarqube-check:
  stage: sonarqube-check
  image: maven:3.8.5-openjdk-17
  tags:
    - ohtu-build-3
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=orgrek-ou-service -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN} -Dsonar.dependencyCheck.jsonReportPath=dependency-check-report.json -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html
  only:
    - main
  needs:
    - job: dependency-check
      artifacts: true

deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-3
  except:
    - schedules
  environment:
    name: development
  only:
    - main
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-dev --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-dev --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_TEST_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-dev deploy/organisaatiorekisteri-api-dev
    - oc set env deploy/organisaatiorekisteri-api-dev API_DB_HOST=$API_DB_HOST_DEV
    - oc set env deploy/organisaatiorekisteri-api-dev API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_DEV
    - oc set env deploy/organisaatiorekisteri-api-dev OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/organisaatiorekisteri-api-dev OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/organisaatiorekisteri-api-dev TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-dev --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_test:
  stage: deploy
  tags:
    - ohtu-build-3
  except:
    - schedules
  environment:
    name: testing
  only:
    - test
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-test --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-test --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_TEST_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-test deploy/organisaatiorekisteri-api-test
    - oc set env deploy/organisaatiorekisteri-api-test API_DB_HOST=$API_DB_HOST_TEST
    - oc set env deploy/organisaatiorekisteri-api-test API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_TEST
    - oc set env deploy/organisaatiorekisteri-api-test OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/organisaatiorekisteri-api-test OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/organisaatiorekisteri-api-test TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-test --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-test --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-test --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_prod:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: production
  except:
    - schedules
  only:
    - prod
  when: manual
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_PROD:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_PROD
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-prod --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-prod --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_PROD_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-prod deploy/organisaatiorekisteri-api-prod
    - oc set env deploy/organisaatiorekisteri-api-prod API_DB_HOST=$API_DB_HOST_PROD
    - oc set env deploy/organisaatiorekisteri-api-prod API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_PROD
    - oc set env deploy/organisaatiorekisteri-api-prod OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/organisaatiorekisteri-api-prod OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/organisaatiorekisteri-api-prod TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisaatiorekisteri-api-prod --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisaatiorekisteri-api-prod --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-api-prod --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_organisation_dev:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: development
  only:
    - organisation-dev
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    # add secrets here
    - oc delete secret generic hy-organisation-application-api-key-dev --ignore-not-found
    - oc create secret generic hy-organisation-application-api-key-dev --from-literal=HY_ORGANISATION_APPLICATION_API_KEY=$HY_ORGANISATION_APPLICATION_TEST_API_KEY
    # list environment variables here
    - oc set env --from=secret/hy-organisation-application-api-key-dev deploy/organisation-api-dev
    - oc set env deploy/organisation-api-dev API_DB_HOST=$API_DB_HOST_ORGANISATION_DEV
    - oc set env deploy/organisation-api-dev API_OU_SERVICE_HOST=$API_OU_SERVICE_HOST_ORGANISATION_DEV
    - oc set env deploy/organisation-api-dev OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/organisation-api-dev OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/organisation-api-dev TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build organisation-api-dev --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/organisation-api-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisation-api-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
